/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import DAO.SachDao;
import Entity.Sach;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import raven.drawer.TabbedForm;

/**
 *
 * @author ACER
 */
public class QL_sach extends TabbedForm {
     private DefaultTableModel model;
    private SachDao sachDao = new SachDao();
    private List<Sach> listSach;
    /**
     * Creates new form QL_sach
     */
    public QL_sach() {
        initComponents();
                init();

    }
    
     private void init() {
        // Khởi tạo model và set lên JTable
        model = new DefaultTableModel(new String[]{
            "Tên Sách", "Thể Loại", "Tác Giả", "Nhà Xuất Bản", "Năm Xuất Bản", "Ngôn Ngữ", "Số Lượng", "Lần Tái Bản"
        }, 0);
        tbl_sach.setModel(model);

        // Load dữ liệu từ database
        loadData();
    }

    private void loadData() {
        listSach = sachDao.getAll();
        fillToTable();
    }

    private void fillToTable() {
        model.setRowCount(0); // Xóa dữ liệu cũ
        for (Sach sach : listSach) {
            model.addRow(new Object[]{
                
                sach.getTenSach(),
                sach.getTheLoai(),
                sach.getTacGia(),
                sach.getNhaXuatBan(),
                sach.getNamXuatBan(),
                sach.getNgonNgu(),
                sach.getSoLuong(),
                sach.getLanTaiBan()
            });
        }
    }
    // tạo form con để thêm thông tin sách  
    private void openFormCon() {
        JDialog formCon = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Thêm sách", true);
        formCon.setSize(850, 200);
        formCon.setLayout(new BorderLayout());

        // Panel chính chứa form nhập liệu
        JPanel panel = new JPanel(new GridLayout(3, 4, 10, 10)); // 2 dòng, 8 cột
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        panel.add(new JLabel("Mã sách:"));
        JTextField txtMaSach = new JTextField();
        panel.add(txtMaSach);

        panel.add(new JLabel("Tên sách:"));
        JTextField txtTenSach = new JTextField();
        panel.add(txtTenSach);

        panel.add(new JLabel("Thể loại:"));
        String[] theLoai = {"Tiểu thuyết", "Khoa học", "Văn học", "Giáo trình"};
        JComboBox<String> cbTheLoai = new JComboBox<>(theLoai);
        panel.add(cbTheLoai);

        panel.add(new JLabel("Tác giả:"));
        JTextField txtTacGia = new JTextField();
        panel.add(txtTacGia);

        panel.add(new JLabel("Nhà xuất bản:"));
        JTextField txtNXB = new JTextField();
        panel.add(txtNXB);

        panel.add(new JLabel("Năm XB:"));
        JTextField txtNamXB = new JTextField();
        panel.add(txtNamXB);

        panel.add(new JLabel("Ngôn ngữ:"));
        JTextField txtNgonNgu = new JTextField();
        panel.add(txtNgonNgu);

        panel.add(new JLabel("Số lượng:"));
        JTextField txtSoLuong = new JTextField();
        panel.add(txtSoLuong);
        
        panel.add(new JLabel("Lần tái bản:"));
        JTextField txtlantaiban = new JTextField();
        panel.add(txtSoLuong);

        // Panel chứa nút Lưu & Hủy
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        JButton btnLuu = new JButton("Lưu");
        JButton btnHuy = new JButton("Hủy");

        btnLuu.addActionListener(e -> {
            JOptionPane.showMessageDialog(formCon, "Lưu thành công!");
            formCon.dispose();
        });

        btnHuy.addActionListener(e -> formCon.dispose());

        buttonPanel.add(btnLuu);
        buttonPanel.add(btnHuy);

        // Thêm vào form con
        formCon.add(panel, BorderLayout.CENTER);
        formCon.add(buttonPanel, BorderLayout.SOUTH);

        // Hiển thị form con
        formCon.setLocationRelativeTo(this);
        formCon.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sach = new javax.swing.JTable();

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");

        jButton4.setText("Tìm kiếm");

        tbl_sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại sách", "Tác giả", "Nhà xuất bản", "Năm xuất bản", "Ngôn ngữ ", "Số lượng", "Lần tái bản"
            }
        ));
        jScrollPane1.setViewportView(tbl_sach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btn_them)
                .addGap(33, 33, 33)
                .addComponent(btn_xoa)
                .addGap(35, 35, 35)
                .addComponent(btn_sua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        openFormCon();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
          int selectedRow = tbl_sach.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn sách cần xóa!");
        return;
    }

    String tenSach = (String) tbl_sach.getValueAt(selectedRow, 0);

    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sách này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        if (sachDao.delete(tenSach)) {
            JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
            loadData(); // Cập nhật lại bảng sau khi xóa
        } else {
            JOptionPane.showMessageDialog(this, "Xóa sách thất bại!");
        }
    }
    }//GEN-LAST:event_btn_xoaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_sach;
    // End of variables declaration//GEN-END:variables
}
