/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JOptionPane;
import static main.forgot.OTP;
/**
 *
 * @author ACER
 */
public class getcodeOtp extends javax.swing.JFrame {

    /**
     * Creates new form getcodeOtp
     */
    public getcodeOtp() {
        initComponents();
        this.setLocationRelativeTo(this);
        setBackground(new Color(0, 0, 0, 0));
        fadeInEffect();
    }
    public void codeOTP(){
        if (txtnhapmaotp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã OTP!!.");
        } else if (txtnhapmaotp.getText().equals(OTP)) {
            JOptionPane.showMessageDialog(this, "OTP hợp lệ! Bạn có thể đổi mật khẩu.");
            newpassword np = new newpassword();
            np.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Mã OTP không đúng!");
        }
    }
    private void fadeInEffect() {
        new Thread(() -> {
            for (double i = 0.0; i <= 1.0; i += 0.1) {
                String s = i + "";
                float f = Float.valueOf(s);
                this.setOpacity(f);
                try {
                    Thread.sleep(50);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundinlogin1 = new login.Backgroundinlogin();
        jPanel2 = new javax.swing.JPanel();
        btn_getcodeOTP = new swing.Button();
        txtnhapmaotp = new swing.TextField();
        jLabel3 = new javax.swing.JLabel();
        btn_back = new swing.Button();
        btn_exit = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundinlogin1.setBlur(jPanel2);

        jPanel2.setOpaque(false);

        btn_getcodeOTP.setForeground(new java.awt.Color(255, 255, 255));
        btn_getcodeOTP.setText("Accept OTP");
        btn_getcodeOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getcodeOTPActionPerformed(evt);
            }
        });

        txtnhapmaotp.setHint("OTP code");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("OTP code:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_getcodeOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtnhapmaotp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnhapmaotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addComponent(btn_getcodeOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        backgroundinlogin1.add(jPanel2);
        jPanel2.setBounds(80, 70, 330, 200);

        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        backgroundinlogin1.add(btn_back);
        btn_back.setBounds(410, 310, 60, 32);

        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("X");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        backgroundinlogin1.add(btn_exit);
        btn_exit.setBounds(430, 10, 50, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundinlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundinlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_getcodeOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getcodeOTPActionPerformed
        codeOTP();
    }//GEN-LAST:event_btn_getcodeOTPActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private login.Backgroundinlogin backgroundinlogin1;
    private swing.Button btn_back;
    private swing.Button btn_exit;
    private swing.Button btn_getcodeOTP;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private swing.TextField txtnhapmaotp;
    // End of variables declaration//GEN-END:variables
}
